export const movementSeedData = [
  'arnold press',
  'assisted dip',
  'back squat',
  'barbell bench press',
  'barbell bent over row',
  'barbell hip thrust',
  'barbell overhead hold',
  'barbell rear delt row',
  'barbell shrug',
  'barbell upright row',
  'barbell lunge',
  'bench press',
  'bicycle crunch',
  'bulgarian split squat',
  'cable fly',
  'cable front raise',
  'cable lateral raise',
  'cable seated row',
  'chest supported t-bar row',
  'clean and jerk',
  'cossack squat',
  'deadlift',
  'dumbbell bent over row',
  'dumbbell front raise',
  'dumbbell incline press',
  'dumbbell lateral raise',
  'dumbbell row',
  'dumbbell seated shoulder press',
  'dumbbell single leg hip thrust',
  'dumbbell skull crusher',
  'dumbbell supinated curl',
  'dumbbell walking lunge',
  'ez bar curl',
  'front squat',
  'face pulls',
  'hammer curl',
  'hang clean',
  'hang high pull',
  'hanging leg raise',
  'incline bench press',
  'incline dumbbell press',
  'jump shrug',
  'kettlebell wood choppers',
  'lat pulldown',
  'lateral raise',
  'leg extension',
  'leg press',
  'leg raises',
  'lying leg curl',
  'machine seated hip abduction',
  'neutral grip pulldown',
  'overhead squat',
  'overhead press',
  'palloff press',
  'pec dec',
  'plank',
  'power snatch',
  'push press',
  'rear laterall raise',
  'reverse cable fly',
  'reverse grip lat pulldown',
  'reverse pec dec',
  'reverse fly',
  'romanian deadlift',
  'rope triceps extension',
  'face pull',
  'seated leg curl',
  'single arm cable curl',
  'single arm pulldown',
  'single arm rope tricep extension',
  'single leg extension',
  'single lying leg curl',
  'snatch',
  'standing cable chops',
  'standing calf raise',
  'suspended leg raise',
  'weighted dip',
  'weighted rope crunch',
  'conventional deadlift',
  'sumo deadlift',
  'conventional grip pullup',
  'wide grip pullup',
  'neutral grip pullup',
  'reverse grip pullup'
]
